### ISSUE TITLE
Кнопка

### ISSUE THREAD

**Issue by timseriakov** [Createira/shelter#2]
https://github.com/Createira/shelter/blob/bad9b72a845d5ab6a8c2e3f270f4565f3d50def1/index.html#L113

1) Почему кнопка? С точки зрения семантики, кнопка в разметки нужна только в том случае, если она производит какое-то действие, к примеру, открывает модальное окно. если действие - переход на другую страницу или скролл страницы к якорю, то нужно использовать обычный тег `<a>`

2) Странно они у тебя взаимодействуют с пользователем - почему курсор Arrow? должен быть Pointer. Это как бы говорит пользователю, что предполагается взаимодействие

3) `btn--big` это модификатор, тогда уже у кнопки должно быть два класса: `btn` (описывает кнопку в общем случае) и
 `btn--big` (модификатор, частный случай)

есть вопросы - обсудим голосом

**Comment by Createira** [comment]
В случае с кнопкой (Make a friend), я думаю там должна быть модалка-форма, но ничего такого нет в макете.
