### ISSUE TITLE
Модификатор без основного стиля

### ISSUE THREAD

**Issue by timseriakov** [Createira/shelter#7]
https://github.com/Createira/shelter/blob/bad9b72a845d5ab6a8c2e3f270f4565f3d50def1/index.html#L63-L71

должно быть
`class="section__text section__text--black"`

` section__text--black` это модификатор, он описывает частный случай и не должен использоваться отдельно от
`section__text` где описан общий стиль. `section__text--black` лишь должен его уточнять, модифицировать

upd. так же у тебя и в других местах, я уже не буду отдельно открывать issue, к примеру почти везде с `btn`

**Comment by Createira** [comment]
Исправлено, к модификаторам добавлены стили основные.
