### ISSUE TITLE
Классы

### ISSUE THREAD

**Issue by timseriakov** [Createira/shelter#8]
https://github.com/Createira/shelter/blob/bad9b72a845d5ab6a8c2e3f270f4565f3d50def1/index.html#L103-L105

`<button class="btn btn--round-left"> 
     <img class="arrow-left (а не arrow--left)" src="/img/long-arrow-alt-left-solid.svg" width="17px" height="20px" alt="{тут опичание производимого действия, а не описание того, как выглядит. слепому на скринридере 'arrow' ничего не скажет }"> 
 </button> `

**Comment by Createira** [comment]
Исправлено
